### ISSUE TITLE
Rename package name from helm-c-yasnippet to helm-yasnippet

### ISSUE THREAD

**Issue by syohex** [emacs-jp/helm-c-yasnippet#4]
I think `-c-` makes no sense. This breaks compatibility for old users, however this package is removed from MELPA, so I suppose this timing is good.

**Comment by myuhe** [comment]
package-name has no system as `define-obsolete-function-alias`.
Changing name is no benefit,  and  will only make user more upset.

**Comment by syohex** [comment]
I see.
